### ISSUE TITLE
Makes Iron Router hang on loading template

### ISSUE THREAD

**Issue by lourd** [DispatchMe/meteor-kernel#1]
Due to this package overriding the default nature of `Tracker.autorun`, for some reason Iron Router will hang on the loading template for a subscription set up in `waitOn` even when the subscription is ready. I'm not sure why, but I don't think it's a good idea to override `Tracker.autorun` since there's a high chance that there's code that needs to run as fast as possible, not relating at all to the visual frame rate.

**Comment by raix** [comment]
Hi @lourd thanks for reporting, it sound like theres a race condition introduced. The `Kernel.autorun` points to the original `Tracker.autorun` you should be able to do:

``` js
Tracker.autorun = Kernel.autorun;
Deps.autorun = Kernel.autorun;
Meteor.autorun = Kernel.autorun;
```

By nature functions executed in the autorun is defered - the Kernel simply throttles these.

We havent added a replacement for `Meteor.setTimeout` and `Meteor.setInterval` and I'm not sure they would solve this.

If its a good idea or not, I think we have to think about performance and this package literally unblocks the UI (I'm saying theres a big difference in responsiveness on older devices)

Can you help us reproduce?

**Comment by raix** [comment]
I ran the iron controller test - it fails but it failes more when Kernel is used.
I'm pushing a new version in a moment - please test and let me know what you think

**Comment by raix** [comment]
✔ dispatch:kernel v0.0.3

**Comment by lourd** [comment]
Sorry for the delay in responding to this.

I still don't think it's a good idea to override the behavior of `Tracker.autorun`. While it may block the UI I think it's important to remember that Tracker is a reactive programming library, not a UI library. It only happens to do that when used with Blaze. If it does block the UI that's an implementation detail of Blaze, not Tracker, and should be fixed there. I think you're crossing concerns by doing this.
